plugin: amazon.aws.aws_ec2
regions:
  - us-east-1           
filters:
  tag:Name: jenkins-server       
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - private-ip-address
compose:
  ansible_host: public_ip_address


    
